name: weeeklyapp
description: App for Weeekly

publish_to: 'none'

version: 1.0.0+9

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: ^0.6.1+1

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "launch_icon.png"

flutter_native_splash:
  color: "#ff6600"
  image: "splash.png"
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/members/we-can/
    - assets/images/logo/
    - assets/images/cover_art/
    - assets/lyrics/we_are/
    - assets/lyrics/we_can/
    - assets/lyrics/we_play/
    - assets/lyrics/boom_chi_ki/
    - assets/lyrics/tension_up/
    - assets/lyrics/hello_me_ost/
    - assets/lyrics/play_game_holiday/

  fonts:
    - family: Vollkorn
      fonts:
        - asset: fonts/Vollkorn.ttf
          style: normal
        - asset: fonts/Vollkorn-Italic.ttf
          style: italic
        - asset: fonts/Vollkorn-Black.ttf
          weight: 900
        - asset: fonts/Vollkorn-BlackItalic.ttf
          weight: 900
          style: italic