name: weeeklyapp
description: App for Weeekly

publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_widget_from_html: ^0.6.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.7+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "launch_icon.png"

flutter_native_splash:
  color: "#ff6600"
  image: "splash.png"
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/members/we-can/
    - assets/images/logo/
    - assets/images/cover_art/
    - assets/lyrics/we_are/
    - assets/lyrics/we_can/
    - assets/lyrics/we_play/
    - assets/lyrics/boom_chi_ki/

  fonts:
    - family: Vollkorn
      fonts:
        - asset: fonts/Vollkorn.ttf
          style: normal
        - asset: fonts/Vollkorn-Italic.ttf
          style: italic
        - asset: fonts/Vollkorn-Black.ttf
          weight: 900
        - asset: fonts/Vollkorn-BlackItalic.ttf
          weight: 900
          style: italic